# STRING is a data type in python...
# 01 : It is a sequence of characters...

a = "Ibad's" # if we use apostrhopie with any word we use double qoutes..

b = '''mahad's ND ibad"s''' # if we use single or double qoutes in our sentence than we have to write it in triple qoutes...

